### ISSUE TITLE
Lots of warnings about CONFIG.DND5E.abilities in dnd5e 2.2

### ISSUE THREAD

**Issue by cs96and** [trdischat/grouproll#39]
When using this module with dnd5e 2.2, I am receiving lots of warning about CONFIG.DND5E.abilities becoming an object...

E.g....

```
Error: The value of CONFIG.DND5E.abilities has been changed to an object. The former value can be acccessed from .label.
Deprecated since Version 2.2
Backwards-compatible support will be removed in Version 2.4
    at Object.logCompatibilityWarning (commons.js:1993:19)
    at Object.toString (config.mjs:1775:19)
    at Object.f [as escapeExpression] (handlebars.min.js:27:3781)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:6:17)
    at h (handlebars.min.js:27:17870)
    at c (handlebars.min.js:27:6899)
    at handlebars.min.js:27:7585
    at Object.<anonymous> (handlebars.min.js:27:7597)
    at Object.c (handlebars.min.js:27:19853)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:10:52)
    at Object.h [as fn] (handlebars.min.js:27:17870)
    at Object.select (foundry.js:8074:26)
    at Object.c (handlebars.min.js:27:19853)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:11:129)
    at c (handlebars.min.js:27:15429)
    at d (handlebars.min.js:27:15744)
    at e (handlebars.min.js:28:22748)
    at renderTemplate (foundry.js:7712:10)
    at async GroupAbilityCheck._renderInner (foundry.js:5946:16)
    at async GroupAbilityCheck._render (foundry.js:5791:19)
```

I think there might be several places in the code where this warning is getting triggered.

**Comment by trdischat** [comment]
Fixed in release 0.11.1.
